name: Test package in conda environment

on:
    pull_request:
    push:
      branches: [main]

jobs:
    test-conda:
      name: Test with conda environment
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout@v4
        - uses: conda-incubator/setup-miniconda@v3
          with:
            auto-update-conda: true
            python-version: "3.10"
        - name: Conda install fenics
          shell: bash -el {0}
          run: conda install -c conda-forge fenics

        - name: Upgrade pip
          shell: bash -l {0}
          run: python3 -m pip install --upgrade pip

        - name: Install package
          shell: bash -l {0}
          run: python3 -m pip install -e .[test]

        - name: Run tests
          shell: bash -l {0}
          run: python3 -m pytest --cov=beat --cov-report=html --cov-report=term-missing -v
